export enum OperationFlags {
    ChannelCreate = 'Kanal Oluşturma',
    ChannelDelete = 'Kanal Silme',
    ChannelUpdate = 'Kanal Güncelleme',
    EmojiCreate = 'Emoji Oluşturma',
    EmojiDelete = 'Emoji Silme',
    EmojiUpdate = 'Emoji Güncelleme',
    Kick = 'Üye Atma',
    Ban = 'Üye Yasaklama',
    RoleCreate = 'Rol Oluşturma',
    RoleDelete = 'Rol Silme',
    RoleUpdate = 'Rol Güncelleme',
    StickerCreate = 'Çıkartma Oluşturma',
    StickerDelete = 'Çıkartma Silme',
    StickerUpdate = 'Çıkartma Güncelleme',
    WebhookCreate = 'Webhook Oluşturma',
    WebhookDelete = 'Webhook Silme',
    WebhookUpdate = 'Webhook Güncelleme',
    VoiceKick = 'Üyeyi Sesten Atma',
    GuildUpdate = 'Sunucu Ayarı Güncelleme',
}
